### ISSUE TITLE
while(child=node.firstChild)

### ISSUE THREAD

**Issue by terrilltang** [bison1994/two-way-data-binding#2]
html代码中44行 这句是不是少了个”=“

**Comment by bison1994** [comment]
不是，赋值语句也是有返回值的，当node.firstChild不存在时，该语句返回null

**Comment by terrilltang** [comment]
为什么while在赋值firstChild并返回true的条件执行之后，child可以一直更新值指向新的childNode，求教。

**Comment by bison1994** [comment]
dom-tree:
A
 | -- B
      | -- C
第一轮循环：
child = B，返回true
第二轮循环：
child = C，返回true
第三轮循环：
child = null，返回false
终止循环

**Comment by terrilltang** [comment]
child不是一直指向的是node.firstChild吗？

**Comment by bison1994** [comment]
现在较忙，我晚点看看再回复您，以前写的我也忘了

**Comment by terrilltang** [comment]
好的；谢谢。
另：我尝试了一下注释while循环中的 文档片段append(child)这句，就会死循环；如果添加文档片段的那句就会正常。

**Comment by terrilltang** [comment]
已经弄懂了，append时会删除原先的节点，直到null。 firstChild一直在变更。
