### ISSUE TITLE
数据改变没有触发对象属性访问器中的set方法,进而视图没有发生变化

### ISSUE THREAD

**Issue by wojiaohanshuai** [bison1994/two-way-data-binding#6]
你好
我在控制台输入  vm.data.text = 'hello';  发现没有触发对象属性访问器中的set方法,进而视图没有发生变化

**Comment by tingtingtinghuang** [comment]
需要这样改变: vm['text']='hello' 或者 vm.text='hello'

**Comment by wojiaohanshuai** [comment]
哦,可以了,,vue是把data中数据绑定到vue实例上! 谢谢了
